"""updating tables

Revision ID: 5bc63fcd9fa1
Revises: abe0e2947f23
Create Date: 2023-07-07 22:25:39.299149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc63fcd9fa1'
down_revision = 'abe0e2947f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.drop_column('categories')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('e_pitch', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('image_1', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('image_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('background', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('application', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('storage', sa.String(), nullable=True))
        batch_op.drop_column('p_image')
        batch_op.drop_column('p_image_2')
        batch_op.drop_column('p_description')
        batch_op.drop_column('p_background')
        batch_op.drop_column('p_name')
        batch_op.drop_column('p_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_price', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('p_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('p_background', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('p_description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('p_image_2', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('p_image', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('storage')
        batch_op.drop_column('application')
        batch_op.drop_column('background')
        batch_op.drop_column('image_2')
        batch_op.drop_column('image_1')
        batch_op.drop_column('description')
        batch_op.drop_column('e_pitch')
        batch_op.drop_column('price')
        batch_op.drop_column('name')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
