"""updating tables

Revision ID: 5e0fb449a9db
Revises: a4aec69b8239
Create Date: 2023-07-07 15:33:15.624621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0fb449a9db'
down_revision = 'a4aec69b8239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_order_items_product_id_products'), 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_order_items_order_id_orders'), 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_items_order_id_orders'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_order_items_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
