"""updating tables

Revision ID: 881e3470fad4
Revises: 5e0fb449a9db
Create Date: 2023-07-07 15:43:04.789089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881e3470fad4'
down_revision = '5e0fb449a9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cart_items_cart_id_cartstuff'), 'cartstuff', ['cart_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_cart_items_product_id_products'), 'products', ['product_id'], ['id'])

    with op.batch_alter_table('cartstuff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cartstuff_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cartstuff', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cartstuff_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cart_items_product_id_products'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cart_items_cart_id_cartstuff'), type_='foreignkey')
        batch_op.drop_column('product_id')
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###
