"""updating tables

Revision ID: c10d2b4ebb0a
Revises: c46ecb37eef3
Create Date: 2023-07-07 22:47:40.029738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10d2b4ebb0a'
down_revision = 'c46ecb37eef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_order_items_product_id_products'), 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_items_product_id_products'), type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
