"""updating tables

Revision ID: c46ecb37eef3
Revises: 5bc63fcd9fa1
Create Date: 2023-07-07 22:45:28.018677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46ecb37eef3'
down_revision = '5bc63fcd9fa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_items_product_id_products', type_='foreignkey')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_status_id_order_status'), 'order_status', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_status_id_order_status'), type_='foreignkey')
        batch_op.drop_column('status_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_order_items_product_id_products', 'products', ['product_id'], ['id'])

    # ### end Alembic commands ###
