"""updating tables

Revision ID: feb8abc59738
Revises: eb229b3491ed
Create Date: 2023-07-07 15:22:16.666307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb8abc59738'
down_revision = 'eb229b3491ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address_2',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_order_status_status'), ['status'])
        batch_op.drop_column('current_status')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('card_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cardholder_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('expiration_month',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('expiration_year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cvv',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))
        batch_op.alter_column('p_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('p_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('ingredients')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('cvv',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('expiration_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('expiration_month',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cardholder_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('card_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_status', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_order_status_status'), type_='unique')
        batch_op.drop_column('status')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.alter_column('address_2',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
